bioResearchSystem/bioResearchSystem.Web/Models/Experiments/ExperimentModel.cs
using bioResearchSystem.Models.Entities;
using bioResearchSystem.Models.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace bioResearchSystem.Web.Models.Experiments
{
    public class ExperimentModel
    {
        public Guid Id { get; set; }
        public string NameExperiment { get; set; }
        public string Goal { get; set; }
        public StatusExperiment StatusExperiment { get; set; }
        public DateTime StartedDate { get; set; }
        public Guid ResearchId { get; set; }
        public Research Research { get; set; }
        public IDictionary<string, int> Result { get; set; }
        public string Data { get; set; }
        public int Kmer { get; set; }

    }
}

bioResearchSystem/bioResearchSystem.Web/Models/Experiments/ExperimentProcess.cs
using bioResearchSystem.Models.Entities;
using bioResearchSystem.Models.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace bioResearchSystem.Web.Models.Experiments
{
    public class ExperimentProcess
        
    {
        public Guid Id { get; set; }
        public StatusExperiment StatusExperiment { get; set; }
        public DateTime StartedDate { get; set; }
        public Guid ResearchId { get; set; }
        public Research Research { get; set; }
        public string Result { get; set; }
        [Required(ErrorMessage ="Experiment data is not defined")]
        public string Data { get; set; }
        public int Kmer{ get; set; }
    }
}

bioResearchSystem/bioResearchSystem.Web/Models/Experiments/ExperimentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace bioResearchSystem.Web.Models.Experiments
{
    public class ExperimentViewModel
    {
    }
}

bioResearchSystem/bioResearchSystem.Web/Controllers/ExperimentsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Ports;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using AutoMapper;
using BioAlgo.BioAlgorthims.Algorithms.KmersComputing;
using bioResearchSystem.Models.Entities;
using bioResearchSystem.Models.Enums;
using bioResearchSystem.Web.Models.Experiments;
using bioResearchSystem.ВLL.Services.Experiments;
using bioResearchSystem.ВLL.Services.Researches;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Newtonsoft.Json;
using SciReport;

namespace bioResearchSystem.Web.Controllers
{
    public class ExperimentsController : Controller
    {
        private readonly IMapper mapper;
        private readonly IResearchService researchService;
        private readonly IExperimentService experimentService;
        private readonly UserManager<AppUser> userManager;

        public ExperimentsController(IMapper mapper, IExperimentService experimentService, IResearchService researchService,
             UserManager<AppUser> userManager)
        {
            this.mapper = mapper;
            this.userManager = userManager;
            this.experimentService = experimentService;
            this.researchService = researchService;
        }

        public async Task<IActionResult> CreateReportXml(string experimentId)
        {
            var experiment = await experimentService.GetExperimentAsync(Guid.Parse(experimentId));
            if (experiment != null)
            {
                var resultDictionary = JsonConvert.DeserializeObject<IDictionary<string, int>>(experiment.JsonResult);
                var xElement = new XElement("experiment-resut-root", resultDictionary.Select(kv => new XElement(kv.Key, kv.Value)));
                var xmlDocument = new XDocument();
                xmlDocument.Add(xElement);
                return File(new MemoryStream(Encoding.Unicode.GetBytes(xmlDocument.ToString().ToArray())), "application/xml", "experiment-result.xml"); ;
            }

            return NotFound();
        }

        public async Task<IActionResult> MyLaboratory()
        {
            var stringedUserId = HttpContext.Session.GetString("userId");
            var user = await userManager.FindByIdAsync(stringedUserId);
            var userExperiments = await experimentService.GetUsersExperiments(user.Id);
            return View(userExperiments);
        }

        [HttpGet]
        public async Task<IActionResult> CreateExperiment(string researchId)
        {
            var research = await researchService.GetResearchAsync(Guid.Parse(researchId));

            var experimentModel = new ExperimentModel()
            {
                Research = research,
                ResearchId = research.Id
            };
            return View(experimentModel);
        }
        [HttpPost]
        public async Task<IActionResult> CreateExperiment(ExperimentModel experimentModel)
        {


            if (ModelState.IsValid)
            {
                var mappedExperiment = mapper.Map<Experimet>(experimentModel);
                mappedExperiment.StatusExperiment = StatusExperiment.NotStarted;
                var experiment = await experimentService.CreateNewExperiment(mappedExperiment);
                return RedirectToAction(nameof(ExperimentProcess), new { id = experiment.Id });
            }
            return View();



        }


        [HttpGet]
        public async Task<IActionResult> ExperimentProcess(Guid id)
        {
            if (id != null)
            {
                var experiment = await experimentService.GetExperimentAsync(id);
                var mappedExperiment = mapper.Map<ExperimentModel>(experiment);
                if (experiment.JsonResult != null) mappedExperiment.Result = JsonConvert.DeserializeObject<IDictionary<string, int>>(experiment.JsonResult);
                return View(mappedExperiment);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> ExperimentProcess(ExperimentProcess exp)
        {
            if (ModelState.IsValid)
            {
                var experiment = await experimentService.CreateNewExperiment(mapper.Map<Experimet>(exp));
                return RedirectToAction(nameof(ExperimentProcess), new { id = experiment.Id });
            }
            return View();

        }


        [HttpGet]
        public async Task<IActionResult> GetData(string id)
        {
            var serialtPort = new SerialPort();
            serialtPort.BaudRate = 9600;
            serialtPort.PortName = "COM4";
            var strb = new StringBuilder();
            var experiment = await experimentService.GetExperimentAsync(Guid.Parse(id));

            serialtPort.Open();
            var result = await Task.Run(() =>
            {
                while (strb.Length <= 1000)
                {
                    var generatedData = serialtPort.ReadLine();
                    strb.Append(generatedData);
                }
                return strb.ToString();
            });
            serialtPort.Close();
            experiment.Data = result;
            experiment.StatusExperiment = StatusExperiment.InProgress;
            await experimentService.UpdeteExperiment(experiment);
            return RedirectToAction(nameof(ExperimentProcess), new { id = experiment.Id });
        }

        [HttpPost]
        public async Task<IActionResult> StratProcessing(ExperimentModel exp)
        {
            if (ModelState.IsValid)
            {
                var kmc = new KMC();
                var experiment = await experimentService.GetExperimentAsync(exp.Id);
                var processedData = kmc.BuildAcidDictionary(exp.Kmer, experiment.Data );
                experiment.JsonResult = JsonConvert.SerializeObject(processedData);
                experiment.StatusExperiment = StatusExperiment.Done;
                await experimentService.UpdeteExperiment(experiment);
                return RedirectToAction(nameof(ExperimentProcess), new { id = experiment.Id });
            }
            return RedirectToAction(nameof(ExperimentProcess), new { id = exp.Id });
        }
    }
}

bioResearchSystem/bioResearchSystem.Web/Views/Experiments/CreateExperiment.cshtml
@model bioResearchSystem.Web.Models.Experiments.ExperimentModel

@{
    ViewData["Title"] = "CreateExperiment";
}



    <h4 class="mono">
        Preparatory experiment information
    </h4>
<hr />
<div class="row">
    <div class="col-lg-10">
        <form asp-action="CreateExperiment">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <div>
                    <h6 class="my-0 pretty-text" >Name Experiment<span style="color:red">*</span></h6>
                    <small class="text-muted">Give short name to experiment</small>
                </div>
                <input asp-for="ResearchId" class="form-control" hidden />
                <input asp-for="NameExperiment" class="form-control" />
                <span asp-validation-for="NameExperiment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div>
                    <h6 class="my-0">Goal <span style="color:red">*</span></h6>
                    <small class="text-muted">Describe your goal this experiment</small>
                </div>
                <textarea asp-for="Goal" class="form-control" ></textarea>
                <span asp-validation-for="Goal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Continue" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

bioResearchSystem/bioResearchSystem.Web/Views/Experiments/ExperimentProcess.cshtml
@model bioResearchSystem.Web.Models.Experiments.ExperimentModel


<div class="container-fluid text-center mt-3">
   <form asp-action="StratProcessing">
        <div class="row content">

            <div class="col-sm-2 sidenav">
                <h6 class="my-0 pretty-text">Report</h6>
                <small class="text-muted pretty-text">Select compatiable format report</small>
                <p><a href='@Url.Action("CreateReportXml", "Experiments", new { experimentId = Model.Id.ToString() }, null)'>XML</a></p>
                <input asp-for="ResearchId" hidden />
                <input asp-for="Id" hidden />
            </div>
            <div class="col-sm-8 text-left">
                <h4 class="pretty-text">@Model.NameExperiment</h4>
                <p class="text-muted pretty-text">@Model.Goal</p>
                <hr>
                <h6 class="pretty-text">Data DNA box</h6>
                <input class="form-control" asp-for="Kmer" min="1" max="1000" value="1" />
                <textarea cols="80" rows="7" class="mt-3" asp-for="Data"></textarea>
                <br />
                <a class="btn btn-info" href='@Url.Action("GetData", "Experiments", new {  id = Model.Id.ToString() }, null)'>Get Data</a>
                <hr />
                @if (Model.Result != null)
                {
                    <table class="table table-bordered  pretty-text">
                        <thead>
                            <tr>
                                <th scope="col">Sub-K-mers</th>
                                <th scope="col">Match</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (KeyValuePair<string, int> kvp in Model.Result)
                            {
                                <tr>
                                    <th scope="row">@kvp.Key</th>
                                    <td>@kvp.Value</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <p class="common-text pretty-text">The experiment has not started yet. Please pick algorithm and generate data</p>
                }
            </div>
            <div class="col-sm-2 sidenav">
                <h6 class="my-0 pretty-text mt-5">Algorithms</h6>

                <small class="text-muted pretty-text">Pick algorithm</small>
                <hr />
                @if (Model.Result is null)
                {
                    <input class="btn btn-primary" type="submit" value="K-mers computing">
                }
                else
                {
                   <span class="badge badge-secondary">K-mers computing</span>
                }
            </div>
        </div>
       </form>
</div>

@section Scripts{
    <script src="~/js/request-to-get-dnajs.js"></script>
}

bioResearchSystem/bioResearchSystem.Web/Views/Experiments/MyLaboratory.cshtml
@model ICollection<bioResearchSystem.Models.Entities.Experimet>
@using bioResearchSystem.Models.Enums
<div class="container-fluid text-center mt-3">
    <form asp-action="StratProcessing">
        <div class="row content">

            <div class="col-sm-2 sidenav">


            </div>
            <div class="col-sm-8 text-left">
                @if (Model.Count() > 0)
                {
                    @foreach (var item in Model)
                    {
                        @if (item.StatusExperiment == StatusExperiment.Done)
                        {
                            <span class="badge badge-success">Done</span>
                        }
                        else if (item.StatusExperiment == StatusExperiment.InProgress)
                        {

                            <span class="badge badge-primary">In Progress</span>
                        }
                        else
                        {
                            <span class="badge badge-secondary">Not Started</span>
                        }

            <div class="media text-muted pt-3">
                <h3 class="rsch-title">
                    <a href='@Url.Action("ExperimentProcess", "Experiments", new {  id = @item.Id.ToString() }, null)'>@item.NameExperiment</a>
                </h3>
                <small class="text-muted">@item.Goal</small>
                <hr />

                @if (item.StatusExperiment == StatusExperiment.Done)
                {
                    <a  class="btn btn-info" href='@Url.Action("ExperimentProcess", "Experiments", new {  id = @item.Id.ToString() }, null)'>View</a>
                }
                else
                {
                    <a class="btn btn-primary" href='@Url.Action("ExperimentProcess", "Experiments", new {  id = @item.Id.ToString() }, null)'>Continue</a>
                }
            </div>
                        <br />
                        <br />
                        <hr />
                    }
                }
            </div>
            <div class="col-sm-2 sidenav">

            </div>
        </div>
    </form>
</div>